"""Calendar helpers for NFL season/week labeling and offline schedules."""

from nfl_oracle.calendar.schedule import (
    NFLVERSE_SCHEDULE_URL,
    NFLVERSE_SCHEDULE_URL_ALIASES,
    ScheduleDensity,
    ScheduledGame,
    SeasonSlateCensus,
    build_gameday_week_index,
    catalog_vs_schedule_density,
    coverage_schedule_census,
    games_for_season,
    games_in_week,
    load_schedules_csv,
    parse_schedules_csv,
    research_schedule_summary,
    resolve_schedule_csv_path,
    schedule_coverage_census,
    season_week_census,
    summarize_schedule_density,
    summarize_season_slate,
    try_load_schedules_csv,
    week_for_gameday,
    weeks_for_season,
)
from nfl_oracle.calendar.season import SeasonWeek, season_label_for_date, season_week_for_date
from nfl_oracle.calendar.slate import (
    SlateResolution,
    opponent_for_team,
    opponents_by_team,
    research_schedule_slate,
    resolve_slate,
    resolve_slate_for_date,
    resolve_slate_for_season_week,
    scheduled_game_to_dict,
)

__all__ = [
    "NFLVERSE_SCHEDULE_URL",
    "NFLVERSE_SCHEDULE_URL_ALIASES",
    "ScheduledGame",
    "ScheduleDensity",
    "SeasonSlateCensus",
    "SlateResolution",
    "SeasonWeek",
    "build_gameday_week_index",
    "catalog_vs_schedule_density",
    "coverage_schedule_census",
    "games_for_season",
    "games_in_week",
    "load_schedules_csv",
    "parse_schedules_csv",
    "research_schedule_summary",
    "resolve_schedule_csv_path",
    "schedule_coverage_census",
    "season_label_for_date",
    "season_week_census",
    "season_week_for_date",
    "scheduled_game_to_dict",
    "opponents_by_team",
    "opponent_for_team",
    "resolve_slate",
    "resolve_slate_for_date",
    "resolve_slate_for_season_week",
    "research_schedule_slate",
    "summarize_schedule_density",
    "summarize_season_slate",
    "try_load_schedules_csv",
    "week_for_gameday",
    "weeks_for_season",
]
